close all
clear all
clc
[a,w,m,~,~]=mong_read('/tests/mongoose/gyro/logs/zv3y00',0);
[aconv,wconv]=mong_conv(a,w,m,0);

T=1/50;
t=0:T:T*(length(a(:,1))-1);
figHandler = figure;
plot(t(100:500),wconv(100:500,3))
ylabel('\fontsize{18}Velocidad angular (^o/s)')
xlabel('\fontsize{18}Tiempo (s)')

magnifyOnFigure(...
        figHandler,...
        'units', 'pixels',...
        'magnifierShape', 'ellipse',...
        'initialPositionSecondaryAxes', [326.933 59.189 164.941 102.65],...
        'initialPositionMagnifier',     [250 342 45 10],...    
        'mode', 'interactive',...    
        'displayLinkStyle', 'straight',...        
        'edgeWidth', 2,...
        'edgeColor', 'black',...
        'secondaryAxesFaceColor', [0.8 0.8 0.8]... 
            ); 
        

